name: Terraform plan

on:
  
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform_backend:
    name: CREATE TERRAFORM BACKEND
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets['AZURE_TENANT_ID'] }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: create backend resource group
        run: |
          az group create --name rg-terraform-state --location eastus

      - name: create backend storage account
        run: |
          az storage account create --name stterraformstate123 --resource-group rg-terraform-state --location eastus --sku Standard_LRS    
      
      - name: create blob container
        run: |
          az storage container create --name tfstate --account-name stterraformstate

  terraform_plan:
    name: TERRAFORM PLAN
    runs-on: ubuntu-latest
    needs: terraform_backend
    # environment: DEV
    # if: github.event_name == 'pull_request'

    defaults:
      run:
        working-directory: ./environment/dev

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets['AZURE_TENANT_ID'] }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        run: terraform init
          

      - name: Terraform Plan
        run: terraform plan

    
    
        
        
        